### ISSUE TITLE
android 平台安装插件后包名不正确

### ISSUE THREAD

**Issue by lysuse** [Mobishift/cordova_plugin_amap_navigation#2]
android 平台安装插件后包名不正确，AMapNavigation包名最后多了一个AMapNavigation

**Comment by mljsgto222** [comment]
修正了AMapNavigation.java、NavigationActivity.java的文件位置

**Comment by suyaoqu** [comment]
为什么我的会闪退

**Comment by mljsgto222** [comment]
@suyaoqu 请提供下你的运行环境，可以的话提供下log

**Comment by suyaoqu** [comment]
@mljsgto222 我装在另一台手机上没有闪退，但报错，错误代码10111

**Comment by mljsgto222** [comment]
@suyaoqu 请问手机的型号和系统是？

**Comment by kong7788** [comment]
android 真机调试，地图不显示，但有声音
