### ISSUE TITLE
android签名包报路径计算失败  status -1

### ISSUE THREAD

**Issue by jnotnull** [Mobishift/cordova_plugin_amap_navigation#4]
代码如下：

        var successCallback = function (message) {
            alert(JSON.stringify(message));
        };
        var errorCallback = function (message) {
            alert("error");
            alert(JSON.stringify(message));
        };

        cordova.plugins.AMapNavigation.navigation({
            lng: 118.78594,
            lat: 31.91514
        }, {
            lng: 118.79019,
            lat: 31.93741
        }, successCallback, errorCallback);`
`

**Comment by mljsgto222** [comment]
高德地图要求android包的签名与api_key与高德开放平台中设置的一致，否则便会出现“路径计算失败 status -1”这个错误

在集成本插件的时候需要检查android项目的manifest.xml中关于amap apikey的设置值是否正确，已经编译产生的包是否正确签名
