### ISSUE TITLE
cordova install error

### ISSUE THREAD

**Issue by dongzhl** [Mobishift/cordova_plugin_amap_navigation#6]
Error: Failed to fetch plugin https://github.com/Mobishift/cordova_plugin_amap_navigation via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963238 Error output:

**Comment by mljsgto222** [comment]
fixed. @dongzhl
